### PR TITLE
Iac and Terratest tests for Secure AKS Construction Set

### PR DESCRIPTION
**Pull request by eedorenko**
- A set of terraform tests for Secure AKS Construction Set
- Iac Pipeline to deploy Secure AKS Construction Set with a Github Actions workflow
- Iac Pipeline to deploy Secure AKS Construction Set with an Azure Pipeline
- Upgraded Flux to v2
- Included Flux V2 installation to IaC pipelines

### CODE REVIEW

**Review by hieunhums — DISMISSED** [review]
LGTM now.
Refactored to Landingzone & Standalone with test and pipelines

**Comment by hieumoscow** [comment]
test action

**Comment by dtzar** [comment]
@hieumoscow Where are we at with this PR?

**Review by hieunhums — APPROVED** [review]
All pipelines are green with GitHub Actions, Azure Pipelines for both Standalone & Landing zone now. Good to merge!

**Review by LaurentLesle — APPROVED** [review]
Very good PR. Thanks for bringing Terratest

**Comment by hieunhums** [comment]
Fix #32 #47 #80

**Comment by eedorenko** [comment]
Hurrah!

**Comment by hieunhums** [comment]
Thanks @eedorenko @sudivate for your contributions :)

**Pull request merged**
